title: "Amisha Gupta"
description: "Aspiring Software Developer | Passionate Learner | Open to Opportunities"
theme: jekyll-theme-minimal

show_downloads: true

author:
  name: "Amisha Gupta"
  email: "amishagupta2704@gmail.com"
  github: "Amisha2700"
  linkedin: "amisha-gupta-567566291"
  resume: "/assets/Amisha_Gupta.pdf"

social_links:
  github: https://github.com/Amisha2700
  linkedin: https://www.linkedin.com/in/amisha-gupta-567566291/
  email: mailto:amishagupta2704@gmail.com
